language: python
services: mongodb
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt -r requirements-ci.txt
before_script:
  - python setup.py develop
script:
  - pytest fireworks
  - pycodestyle fireworks
  - source fireworks/tests/cmd_line_test.sh
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ajain@lbl.gov
      - dkgunter@lbl.gov
      - shyuep@gmail.com
      - xqu@lbl.gov
      - g.petretto@gmail.com
    on_success: change
    on_failure: always
